server:
   port: 8080

spring:
   datasource:
      url: jdbc:mysql://smoothstack-project.cqxybfmjssty.us-east-2.rds.amazonaws.com:3306/utopia
      username: admin
      password: password
   jpa:
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            
logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
    file: /logs/application-debug.log