server:
   port: 8080

spring:
   datasource:
      url: jdbc:mysql://smoothstack-project.cqxybfmjssty.us-east-2.rds.amazonaws.com:3306/utopia
      username: nouser
      password: nopass
      
#spring:
#   datasource:
#      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/utopia
#      username: root
#      password: eb9TcK9Rfx!#
      
   jpa:
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl